CHARACTER_DATA = [
    {"name": "Spider-Man", "education": "High school student", "height": 178, "identity": "Secret",
     "universe": "Marvel Universe", "weight": 76.2},
    {"name": "Iron Man", "education": "M.S. in electrical engineering and physics", "height": 198,
     "identity": "Publicly known", "universe": "Marvel Universe", "weight": 102.1},
    {"name": "Captain America", "education": "High school graduate", "height": 188,
     "identity": "Publicly known", "universe": "Marvel Universe", "weight": 108.0},
    {"name": "Thor", "education": "Tutored by Asgardian scholars", "height": 198,
     "identity": "Publicly known", "universe": "Marvel Universe", "weight": 290.0},
    {"name": "Hulk", "education": "Ph.D. in nuclear physics", "height": 244, "identity": "Publicly known",
     "universe": "Marvel Universe", "weight": 635.0},
    {"name": "Wolverine", "education": "Unrevealed", "height": 160, "identity": "Publicly known",
     "universe": "Marvel Universe", "weight": 136.1},
    {"name": "Black Widow", "education": "KGB training", "height": 170, "identity": "Publicly known",
     "universe": "Marvel Universe", "weight": 59.0},
    {"name": "Doctor Strange", "education": "M.D. in neurosurgery", "height": 185,
     "identity": "Publicly known", "universe": "Marvel Universe", "weight": 82.0},
    {"name": "Black Panther", "education": "Ph.D. in physics", "height": 183, "identity": "Publicly known",
     "universe": "Marvel Universe", "weight": 91.0},
    {"name": "Scarlet Witch", "education": "Unrevealed", "height": 170, "identity": "Publicly known",
     "universe": "Marvel Universe", "weight": 60.0}
]

MOST_COMMON_CHARACTER_NAMES = [
    "Darkstar",
    "Darwin",
    "Captain Britain (Ultimate)",
    "Captain Stacy",
    "Dragon Man",
    "Devos",
    "Sabretooth (Ultimate)",
    "Sage",
    "Lady Mastermind",
    "Count Nefaria",
    "Crimson Dynamo",
    "Cyclops (X-Men: Battle of the Atom)",
    "Ravenous",
    "Red Ghost",
    "Centennial"
]
